#define VERSION_CHAR "2.74"
#define VERSION_TCHAR _T(VERSION_CHAR)
#define VERSION_1 2
#define VERSION_2 7
#define VERSION_3 4
#define VERSION_YEAR "2004"
#define VERSION_YEAR_T _T(VERSION_YEAR)

#define IDI_MAINICON                    101
#define IDI_DISABLEICON                 102
#define IDD_SEL                         103
#define IDI_AUTOICON                    104
#define IDI_LEARNICON                   105
#define IDD_ABOUT                       106
#define IDD_OPTIONS                     108
#define IDR_OPTIONSMENU                 109
#define IDI_MAIN2ICON                   110
#define IDB_CLOSE                       111
#define IDI_TRAYMAIN                    113
#define IDB_CLOSE_SEL                   114
#define IDB_BLUE                        115
#define IDB_LIGHT                       116
#define IDB_HOUSE                       117
#define IDI_OPT_TODAY                   118
#define IDI_OPT_TASK                    119
#define IDI_OPT_TASK_SEL                120
#define IDI_OPT_TODAY_SEL               121
#define IDI_OK_SEL                      125
#define IDI_OK                          126
#define IDD_ORDER                       127
#define IDI_BORDER_ICON                 128
#define IDD_CONTROL                     129
#define IDI_VOLUME                      129
#define IDI_BIG_BORDER                  130
#define IDI_MYCLOSE                     131
#define IDI_MYCLOSE_SEL                 132
#define IDI_ICON1                       133
#define IDI_2CLOSE_SEL                  133
#define IDI_ICON2                       134
#define IDI_2OK_SEL                     134
#define IDI_ICON3                       135
#define IDI_2CLOSE                      135
#define IDI_ICON4                       136
#define IDI_2OK                         136
#define IDB_CLOSE2                      137
#define IDB_CLOSE2_SEL                  138
#define IDC_ACTIONLIST                  1000
#define IDC_MAINSTATIC                  1002
#define IDC_SPEED                       1003
#define IDC_ACCEL                       1004
#define IDC_EXIT                        1007
#define IDC_SHORT_SPIN                  1009
#define IDC_SHORT                       1010
#define IDC_LONG                        1011
#define IDC_ORDER_1                     1011
#define IDC_LONG_SPIN                   1012
#define IDC_ORDER_2                     1012
#define IDC_ORDER_3                     1013
#define IDC_ORDER_4                     1014
#define IDC_ORDER_5                     1015
#define IDC_ORDER_6                     1016
#define IDC_SLIDER                      1017
#define IDC_MUTE                        1018
#define IDC_OK                          1019
#define IDM_ABOUT                       40001
#define IDM_ACTIONS                     40002
#define IDM_EXITAPP                     40003
